version: "3.2"

services:
    nginx:
        build:
            context: ./docker/nginx
        image: nginx:whmcs-reseller
        networks:
            reseller:
                aliases:
                    - wordpress.test
                    - whmcs.test
                    - pma.test
        environment:
            - CERT_PATH=/etc/nginx/certs
            - WORDPRESS_SERVER_NAME=wordpress.test
            - WORDPRESS_CERT_PATH=
            - WORDPRESS_CERT_KEY_PATH=
            - WHMCS_SERVER_NAME=whmcs.test
            - WHMCS_CERT_PATH=
            - WHMCS_CERT_KEY_PATH=
            - PMA_SERVER_NAME=pma.test
            - PMA_CERT_PATH=
            - PMA_CERT_KEY_PATH=
            - SERVER_REAL_IP=172.16.254.0/24
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app/wordpress:/srv/wordpress:ro
            - ./app/whmcs_data:/srv/whmcs:ro
            - ./app/phpmyadmin:/srv/phpmyadmin:ro
            - ./app/certs:/etc/nginx/certs:ro
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - whmcs
            - wordpress
    whmcs:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/whmcs_data:/var/www/whmcs
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
    wordpress:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/wordpress:/var/www/html
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
    phpmyadmin:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/phpmyadmin:/var/www/html
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
    cron:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/whmcs_data:/var/www/whmcs
            - ./app/wordpress:/var/www/html
            - ./app/cron:/cron
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        command:
            - start-cron
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        user: ${USERID:-1000}:${GROUPID:-1000}
        networks:
            - reseller
        environment:
            - MYSQL_ROOT_PASSWORD=888888
            - MYSQL_USER=test
            - MYSQL_PASSWORD=888888
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d
            - ./mysql_data:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        healthcheck:
            test:
                - "CMD"
                - "mysqladmin"
                - "ping"
                - "--user=test"
                - "--password=888888"
                - "-h"
                - "localhost"
            timeout: 5s
            retries: 10
        restart: unless-stopped
    smtp:
        image: namshi/smtp
        restart: unless-stopped
        networks:
            reseller:
                ipv4_address: 172.16.254.8
                aliases: 
                    - smtp.test
    sftp:
        image: atmoz/sftp
        networks:
            - reseller
        volumes:
            - ./app:/home/${USERID:-1000}/upload
        ports:
            - "2222:22"
        command:
            - ${USERID:-1000}:${SFTP_PASSWORD:-password}:${USERID:-1000}:${GROUPID:-1000}

networks:
    reseller:
        driver: bridge
        ipam:
            driver: default
            config: 
                - subnet: 172.16.254.0/24
