version: "3.2"

services:
    nginx:
        build:
            context: ./docker/nginx
        image: nginx:whmcs-reseller
        networks:
            reseller:
                aliases:
                    - wordpress.test
                    - whmcs.test
                    - pma.test
        environment:
            - CERT_PATH=/etc/nginx/certs
            - WORDPRESS_SERVER_NAME=wordpress.test
            - WORDPRESS_CERT_PATH=
            - WORDPRESS_CERT_KEY_PATH=
            - WHMCS_SERVER_NAME=whmcs.test
            - WHMCS_CERT_PATH=
            - WHMCS_CERT_KEY_PATH=
            - WHMCS_BRIDGE_URL=
            - PMA_SERVER_NAME=pma.test
            - PMA_CERT_PATH=
            - PMA_CERT_KEY_PATH=
            - REAL_IP_FROM=172.16.0.0/12
            - SERVER_ADDR=
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app/wordpress:/srv/wordpress:ro
            - ./app/whmcs_data:/srv/whmcs:ro
            - ./app/phpmyadmin:/srv/phpmyadmin:ro
            - ./app/certs:/etc/nginx/certs:ro
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - whmcs
            - wordpress
    whmcs:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/whmcs_data:/var/www/whmcs
            - ./app/php/php-fpm.ini:/usr/local/etc/conf.d/99_custom.ini
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
            - memcached
    wordpress:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/wordpress:/var/www/html
            - ./app/php/php-fpm.ini:/usr/local/etc/conf.d/99_custom.ini
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
            - memcached
    phpmyadmin:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/phpmyadmin:/var/www/html
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
    cron:
        build:
            context: ./docker/php
        image: php:7.2-whmcs-reseller
        networks:
            - reseller
        environment:
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        volumes:
            - ./app/whmcs_data:/var/www/whmcs
            - ./app/wordpress:/var/www/html
            - ./app/cron:/cron
            - ./app/php/php-fpm.ini:/usr/local/etc/conf.d/99_custom.ini
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        command:
            - start-cron
        depends_on:
            - mysql
            - memcached
    mysql:
        image: mysql:5.7
        user: ${USERID:-1000}:${GROUPID:-1000}
        networks:
            - reseller
        environment:
            - MYSQL_ROOT_PASSWORD=888888
            - MYSQL_USER=test
            - MYSQL_PASSWORD=888888
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d
            - ./mysql_data:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        healthcheck:
            test:
                - "CMD"
                - "mysqladmin"
                - "ping"
                - "--user=test"
                - "--password=888888"
                - "-h"
                - "localhost"
            timeout: 5s
            retries: 10
        restart: unless-stopped
    smtp:
        image: namshi/smtp
        restart: unless-stopped
        networks:
            reseller:
                ipv4_address: 172.16.254.8
                aliases: 
                    - smtp.test
     php-ssh:
        build:
            context: ./docker/php-ssh
        image: php:7.2-whmcs-reseller-ssh
        networks:
            reseller:
        ports:
            - "2222:22"
        environment:
            - SSH_USERS=user:1000:1000:/bin/bash
            - SSH_ENABLE_PASSWORD_AUTH=true
        volumes:
            - ./app:/app
            - ./setpasswd.sh:/etc/entrypoint.d/setpasswd.sh:ro
            - /usr/share/zoneinfo/Asia/Jakarta:/etc/localtime
        restart: unless-stopped
        depends_on:
            - mysql
            - memcached
     memcached:
        image: memcached:alpine
        restart: unless-stopped
        networks:
            - reseller
    
networks:
    reseller:
        driver: bridge
        ipam:
            driver: default
            config: 
                - subnet: 172.16.254.0/24
